In [1]:
# Standard setup for Kedro + Jupyter integration
import os
from pathlib import Path
from kedro.framework.startup import bootstrap_project
from kedro.framework.session import KedroSession
from kedro.framework.project import configure_project

# 1. Find the project root (assuming notebook is in notebooks/ folder)
project_path = Path.cwd().parent  # Adjust if your notebook is deeper
print(project_path)

# 2. Bootstrap the Kedro project
# if not (project_path / ".kedro.yml").exists():
#     raise ValueError(f"Kedro project not found at {project_path}")

bootstrap_project(project_path)
configure_project(project_path.name)

# 3. Create a session and load the catalog
session = KedroSession.create(project_path=project_path)
context = session.load_context()

# 4. Make catalog available
catalog = context.catalog

[04/19/25 22:25:38] INFO     Using                                                                  ]8;id=86149;file:///Users/vishalsharma/miniforge3/envs/uc_env/lib/python3.10/site-packages/kedro/framework/project/__init__.py\__init__.py]8;;\:]8;id=965161;file:///Users/vishalsharma/miniforge3/envs/uc_env/lib/python3.10/site-packages/kedro/framework/project/__init__.py#270\270]8;;\
                             '/Users/vishalsharma/miniforge3/envs/uc_env/lib/python3.10/site-packag
                             es/kedro/framework/project/rich_logging.yml' as logging configuration.

/Users/vishalsharma/Downloads/urban_company/uc_no_response

                    WARNING  /Users/vishalsharma/miniforge3/envs/uc_env/lib/python3.10/site-package ]8;id=71022;file:///Users/vishalsharma/miniforge3/envs/uc_env/lib/python3.10/warnings.py\warnings.py]8;;\:]8;id=758035;file:///Users/vishalsharma/miniforge3/envs/uc_env/lib/python3.10/warnings.py#109\109]8;;\
                             s/kedro/io/data_catalog.py:165: KedroDeprecationWarning: `DataCatalog`
                             has been deprecated and will be replaced by `KedroDataCatalog`, in
                             Kedro 1.0.0.Currently some `KedroDataCatalog` APIs have been retained
                             for compatibility with `DataCatalog`, including the `datasets`
                             property and the `get_datasets`, `_get_datasets`, `add`,` list`,
                             `add_feed_dict`, and `shallow_copy` methods. These will be removed or
                             replaced with updated alternatives in Kedro 1.0.0. For more details,
                             refer to the documentation:
                             https://docs.kedro.org/en/stable/data/index.html#kedrodatacatalog-expe
                             rimental-feature
                               warnings.warn(

[04/19/25 22:25:40] WARNING  /Users/vishalsharma/miniforge3/envs/uc_env/lib/python3.10/site-package ]8;id=619622;file:///Users/vishalsharma/miniforge3/envs/uc_env/lib/python3.10/warnings.py\warnings.py]8;;\:]8;id=703515;file:///Users/vishalsharma/miniforge3/envs/uc_env/lib/python3.10/warnings.py#109\109]8;;\
                             s/mlflow/pyfunc/utils/data_validation.py:186: UserWarning: [33mAdd
                             type hints to the `predict` method to enable data validation and
                             automatic signature inference during model logging. Check
                             https://mlflow.org/docs/latest/model/python_model.html#type-hint-usage
                             -in-pythonmodel for more details.[0m
                               color_warning(

                    INFO     Registering new custom resolver: 'km.random_name'                    ]8;id=921833;file:///Users/vishalsharma/miniforge3/envs/uc_env/lib/python3.10/site-packages/kedro_mlflow/framework/hooks/mlflow_hook.py\mlflow_hook.py]8;;\:]8;id=773333;file:///Users/vishalsharma/miniforge3/envs/uc_env/lib/python3.10/site-packages/kedro_mlflow/framework/hooks/mlflow_hook.py#65\65]8;;\

                    INFO     The 'tracking_uri' key in mlflow.yml is relative            ]8;id=550493;file:///Users/vishalsharma/miniforge3/envs/uc_env/lib/python3.10/site-packages/kedro_mlflow/config/kedro_mlflow_config.py\kedro_mlflow_config.py]8;;\:]8;id=40348;file:///Users/vishalsharma/miniforge3/envs/uc_env/lib/python3.10/site-packages/kedro_mlflow/config/kedro_mlflow_config.py#293\293]8;;\
                             ('server.mlflow_(tracking|registry)_uri = mlruns'). It is
                             converted to a valid uri:
                             'file:///Users/vishalsharma/Downloads/urban_company/uc_no_r
                             esponse/mlruns'

                    WARNING  /Users/vishalsharma/miniforge3/envs/uc_env/lib/python3.10/site-package ]8;id=259995;file:///Users/vishalsharma/miniforge3/envs/uc_env/lib/python3.10/warnings.py\warnings.py]8;;\:]8;id=461650;file:///Users/vishalsharma/miniforge3/envs/uc_env/lib/python3.10/warnings.py#109\109]8;;\
                             s/kedro/io/data_catalog.py:165: KedroDeprecationWarning: `DataCatalog`
                             has been deprecated and will be replaced by `KedroDataCatalog`, in
                             Kedro 1.0.0.Currently some `KedroDataCatalog` APIs have been retained
                             for compatibility with `DataCatalog`, including the `datasets`
                             property and the `get_datasets`, `_get_datasets`, `add`,` list`,
                             `add_feed_dict`, and `shallow_copy` methods. These will be removed or
                             replaced with updated alternatives in Kedro 1.0.0. For more details,
                             refer to the documentation:
                             https://docs.kedro.org/en/stable/data/index.html#kedrodatacatalog-expe
                             rimental-feature
                               warnings.warn(

[04/19/25 22:25:41] WARNING  /Users/vishalsharma/miniforge3/envs/uc_env/lib/python3.10/site-package ]8;id=378864;file:///Users/vishalsharma/miniforge3/envs/uc_env/lib/python3.10/warnings.py\warnings.py]8;;\:]8;id=118725;file:///Users/vishalsharma/miniforge3/envs/uc_env/lib/python3.10/warnings.py#109\109]8;;\
                             s/kedro/framework/project/__init__.py:347: UserWarning: The
                             'uc_no_response.pipelines.data_processing' module does not expose a
                             'create_pipeline' function, so no pipelines defined therein will be
                             returned by 'find_pipelines'.
                               warnings.warn(

                    WARNING  /Users/vishalsharma/miniforge3/envs/uc_env/lib/python3.10/site-package ]8;id=21735;file:///Users/vishalsharma/miniforge3/envs/uc_env/lib/python3.10/warnings.py\warnings.py]8;;\:]8;id=545876;file:///Users/vishalsharma/miniforge3/envs/uc_env/lib/python3.10/warnings.py#109\109]8;;\
                             s/kedro/framework/project/__init__.py:347: UserWarning: The
                             'uc_no_response.pipelines.modeling' module does not expose a
                             'create_pipeline' function, so no pipelines defined therein will be
                             returned by 'find_pipelines'.
                               warnings.warn(

                    WARNING  /Users/vishalsharma/miniforge3/envs/uc_env/lib/python3.10/site-package ]8;id=321827;file:///Users/vishalsharma/miniforge3/envs/uc_env/lib/python3.10/warnings.py\warnings.py]8;;\:]8;id=385994;file:///Users/vishalsharma/miniforge3/envs/uc_env/lib/python3.10/warnings.py#109\109]8;;\
                             s/kedro/framework/project/__init__.py:347: UserWarning: The
                             'uc_no_response.pipelines.evaluation' module does not expose a
                             'create_pipeline' function, so no pipelines defined therein will be
                             returned by 'find_pipelines'.
                               warnings.warn(

                    INFO     Kedro is sending anonymous usage data with the sole purpose of improving ]8;id=377459;file:///Users/vishalsharma/miniforge3/envs/uc_env/lib/python3.10/site-packages/kedro_telemetry/plugin.py\plugin.py]8;;\:]8;id=336685;file:///Users/vishalsharma/miniforge3/envs/uc_env/lib/python3.10/site-packages/kedro_telemetry/plugin.py#233\233]8;;\
                             the product. No personal data or IP addresses are stored on our side. If
                             you want to opt out, set the `KEDRO_DISABLE_TELEMETRY` or `DO_NOT_TRACK`
                             environment variables, or create a `.telemetry` file in the current
                             working directory with the contents `consent: false`. Read more at
                             https://docs.kedro.org/en/stable/configuration/telemetry.html

In [2]:
# import necessary libraries
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
%matplotlib inline

import warnings
warnings.filterwarnings("ignore")

In [3]:
# load the data
df = catalog.load("raw_data")

[04/19/25 22:25:43] INFO     Loading data from raw_data (CSVDataset)...                         ]8;id=347630;file:///Users/vishalsharma/miniforge3/envs/uc_env/lib/python3.10/site-packages/kedro/io/data_catalog.py\data_catalog.py]8;;\:]8;id=584323;file:///Users/vishalsharma/miniforge3/envs/uc_env/lib/python3.10/site-packages/kedro/io/data_catalog.py#401\401]8;;\

In [4]:
# check for null 
df.isnull().sum() * 100 / len(df)

Unnamed: 0                          0.000
NR_experienced_on_request           0.000
no_of_supercats_tried_last_30d     15.075
no_of_supercats_tried_last_90d     15.075
no_of_supercats_tried_last_365d    15.075
no_of_deliveries_last_30d          15.075
no_of_deliveries_last_90d          15.075
no_of_deliveries_last_365d         15.075
service_deliverd_aov_last_30d      58.910
service_deliverd_aov_last_90d      37.230
service_deliverd_aov_last_365d     20.735
most_deliverd_supercat             15.075
income_segment                     75.295
gender                              0.085
user_state_platform                15.075
days_on_platform                   15.075
NR_experienced_last_365d            0.085
revenues_next_6_months              7.610
request_id                          0.000
dtype: float64

In [5]:
threshold = 0.8 * len(df.columns)

# Drop rows where more than 80% of features are NULL
df_cleaned = df.dropna(thresh=len(df.columns) - threshold + 1)

In [6]:
df_cleaned.isnull().sum() * 100 / len(df_cleaned)

Unnamed: 0                          0.000000
NR_experienced_on_request           0.000000
no_of_supercats_tried_last_30d     15.002752
no_of_supercats_tried_last_90d     15.002752
no_of_supercats_tried_last_365d    15.002752
no_of_deliveries_last_30d          15.002752
no_of_deliveries_last_90d          15.002752
no_of_deliveries_last_365d         15.002752
service_deliverd_aov_last_30d      58.875044
service_deliverd_aov_last_90d      37.176600
service_deliverd_aov_last_365d     20.667567
most_deliverd_supercat             15.002752
income_segment                     75.273983
gender                              0.000000
user_state_platform                15.002752
days_on_platform                   15.002752
NR_experienced_last_365d            0.000000
revenues_next_6_months              7.531402
request_id                          0.000000
dtype: float64

In [7]:
df_cleaned[['request_id', 
            'service_deliverd_aov_last_30d', 'no_of_deliveries_last_30d', 
            'service_deliverd_aov_last_90d', 'no_of_deliveries_last_90d', 
            'service_deliverd_aov_last_365d', 'no_of_deliveries_last_365d', 
            ]].sample(5)

,request_id,service_deliverd_aov_last_30d,no_of_deliveries_last_30d,service_deliverd_aov_last_90d,no_of_deliveries_last_90d,service_deliverd_aov_last_365d,no_of_deliveries_last_365d
14139,311efd6a-8928-4492-8c24-49ea32c633bc,NaN,NaN,NaN,NaN,NaN,NaN
5854,1b82d0e8-81d0-42ec-94ec-ee53441cdd01,NaN,NaN,NaN,NaN,NaN,NaN
18065,00f31525-4ad2-43c2-a68b-ff35e4067f07,724.0,1.0,685.5,2.0,752.333333,3.0
18496,4bec9abd-6d16-4614-a986-525e124b1753,NaN,0.0,3703.0,1.0,1754.000000,5.0
915,17ea592e-0256-4b61-96f8-fd21d6deb518,NaN,0.0,828.0,2.0,754.125000,8.0

In [8]:
df_cleaned.loc[df_cleaned['no_of_deliveries_last_30d'] == 0, 'service_deliverd_aov_last_30d'] = 0
df_cleaned.loc[df_cleaned['no_of_deliveries_last_90d'] == 0, 'service_deliverd_aov_last_90d'] = 0
df_cleaned.loc[df_cleaned['no_of_deliveries_last_365d'] == 0, 'service_deliverd_aov_last_365d'] = 0

In [9]:
df_cleaned.isnull().sum() * 100 / len(df_cleaned)

Unnamed: 0                          0.000000
NR_experienced_on_request           0.000000
no_of_supercats_tried_last_30d     15.002752
no_of_supercats_tried_last_90d     15.002752
no_of_supercats_tried_last_365d    15.002752
no_of_deliveries_last_30d          15.002752
no_of_deliveries_last_90d          15.002752
no_of_deliveries_last_365d         15.002752
service_deliverd_aov_last_30d      15.002752
service_deliverd_aov_last_90d      15.002752
service_deliverd_aov_last_365d     15.002752
most_deliverd_supercat             15.002752
income_segment                     75.273983
gender                              0.000000
user_state_platform                15.002752
days_on_platform                   15.002752
NR_experienced_last_365d            0.000000
revenues_next_6_months              7.531402
request_id                          0.000000
dtype: float64

In [10]:
df_cleaned[df_cleaned['no_of_supercats_tried_last_30d'].isnull()][['no_of_supercats_tried_last_30d', 'no_of_supercats_tried_last_90d', 'no_of_supercats_tried_last_365d']]

,no_of_supercats_tried_last_30d,no_of_supercats_tried_last_90d,no_of_supercats_tried_last_365d
2,NaN,NaN,NaN
7,NaN,NaN,NaN
14,NaN,NaN,NaN
17,NaN,NaN,NaN
19,NaN,NaN,NaN
...,...,...,...
19980,NaN,NaN,NaN
19983,NaN,NaN,NaN
19989,NaN,NaN,NaN
19990,NaN,NaN,NaN
19995,NaN,NaN,NaN

In [ ]:
coexisting_nulls = [
    'no_of_supercats_tried_last_30d', 'no_of_supercats_tried_last_90d', 'no_of_supercats_tried_last_365d',
    'no_of_deliveries_last_30d', 'no_of_deliveries_last_90d', 'no_of_deliveries_last_365d',
    'service_deliverd_aov_last_30d', 'service_deliverd_aov_last_90d', 'service_deliverd_aov_last_365d', 
]
df_cleaned.dropna(inplace=True, subset=coexisting_nulls)

In [12]:
df_cleaned.isnull().sum() * 100 / len(df_cleaned)

Unnamed: 0                          0.000000
NR_experienced_on_request           0.000000
no_of_supercats_tried_last_30d      0.000000
no_of_supercats_tried_last_90d      0.000000
no_of_supercats_tried_last_365d     0.000000
no_of_deliveries_last_30d           0.000000
no_of_deliveries_last_90d           0.000000
no_of_deliveries_last_365d          0.000000
service_deliverd_aov_last_30d       0.000000
service_deliverd_aov_last_90d       0.000000
service_deliverd_aov_last_365d      0.000000
most_deliverd_supercat              0.000000
income_segment                     73.217545
gender                              0.000000
user_state_platform                 0.000000
days_on_platform                    0.000000
NR_experienced_last_365d            0.000000
revenues_next_6_months              5.398881
request_id                          0.000000
dtype: float64